version: 2

project_name: patchline

builds:
  - id: patchline
    main: ./cmd/patchline
    binary: patchline
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/AksharP5/Patchline/internal/cli.Version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: patchline
    repository:
      owner: AksharP5
      name: tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/AksharP5/Patchline"
    description: "Streamline OpenCode plugin updates."
    install: |
      bin.install "patchline"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Version }}-next"
